### ISSUE TITLE
HEADER - Replace logo SVG

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#1]
Please, replace this SVG for the one below:

**logo-small.svg**
https://drive.google.com/file/d/1C5jb8nxYHzZp6lQC0i6gJN8kh0A4v2C-/view?usp=sharing

**Comment by pedrojovelli** [comment]
Item não foi ajustado. Há um espaço entre Rio e Slum. 

No SVG está grudado (1 única palavra RioSlum ).

**Comment by robanquieri** [comment]
Você não especificou qual logo deveria ser substituído, logo eu sobrescrevi a imagem indicada no link que é o logo mobile.

**Comment by pedrojovelli** [comment]
corói. Podcrer !
