### ISSUE TITLE
WORK - Don Curvino Replace images

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#10]
I've checked on my phone and these photos seems to be in really low quality.

These're better ones:

https://drive.google.com/drive/folders/1yhkoKTlEkbTUdcSyX9E_VA1O6Ljk02tr?usp=sharing
![290x200_doncurvino](https://user-images.githubusercontent.com/15367213/42129353-ea84b00e-7c98-11e8-8e4c-6eb54ab37888.jpg)
![310x200_doncurvino](https://user-images.githubusercontent.com/15367213/42129354-ec0ad35e-7c98-11e8-9cff-ae1e9e88a3c0.jpg)
![380x200_doncurvino](https://user-images.githubusercontent.com/15367213/42129355-ee83fe1c-7c98-11e8-8891-63b1fc360721.jpg)

**Comment by robanquieri** [comment]
Não estão com os nomes corretos.

**Comment by pedrojovelli** [comment]
XS
https://drive.google.com/file/d/1mwRBt82p1iYRlgKk5ujVF4vld26q04Z4/view?usp=sharing

SM
https://drive.google.com/file/d/17DOoxcPT8CaAvuYxK1oeV3fC1g8kG3SB/view?usp=sharing

MD
https://drive.google.com/file/d/1PFT-hr2ycA15ZjgReYB6Iw0AZLWnevJN/view?usp=sharing

**Comment by robanquieri** [comment]
done
