### ISSUE TITLE
WORK - Add one more image at the bottom

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#11]
Adicionar mais 1 imagem grande no final da galeria ( texto do hover: RioSlum Studio/Full Portfolio _

Ex.: 

![screen shot 2018-06-24 at 1 06 10 pm](https://user-images.githubusercontent.com/15367213/41820923-9061ff2a-77af-11e8-87d0-9aad7da20ea0.png)

Este link irá levar para nosso portfolio em PDF

==========

At the bottom of the Work section, add a large, almost banner image keeping with the standard of the current website. This will contain an image of Rio, and then when you hover over it, it will say – “RioSlum Studio/Full Portfolio”

**Comment by robanquieri** [comment]
Você não adicionou as imagens desse formato no drive na pasta _**Format One**_

**Comment by pedrojovelli** [comment]
imagens Format One:
https://drive.google.com/drive/folders/1uaUnLOlfEhArq_7HxVq7klYIxMfY9sZC?usp=sharing

PDF do portfolio:
[RioSlum_Portfolio_2018.pdf](https://github.com/robanquieri/rioslumstudio/files/2133055/RioSlum_Portfolio_2018.pdf)

**Comment by robanquieri** [comment]
Faltou a xs.jpg

**Comment by robanquieri** [comment]
Faltaram as imagens do carousel

**Comment by robanquieri** [comment]
Por favor, siga os nomes corretos!!!

**Comment by robanquieri** [comment]
Done
