### ISSUE TITLE
WORK - Agora replace images

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#11]
Imagens estavam em baixa qualidade.

Segue imagens melhores. Substituir por favor.

https://drive.google.com/drive/folders/1etCbBtQd4f_r6i9KNzTKiUfEnHUmQq4a?usp=sharing

![sm](https://user-images.githubusercontent.com/15367213/42129379-8686e58a-7c99-11e8-8813-5c9f02488d89.jpg)
![xs](https://user-images.githubusercontent.com/15367213/42129380-86a9999a-7c99-11e8-8b3b-6de67feb3689.jpg)

**Comment by robanquieri** [comment]
done
