### ISSUE TITLE
WORK Gallery Behaviour

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#12]
Once inside a Work gallery, when you close it, it should take you back to the same place on the previous screen. 

O Comportamento agora é que você clica em alguma imagem de WORK. Ele abre a galeria, mas quando fecha, a página volta ao topo e não na altura onde estava anteriormente.

**Comment by robanquieri** [comment]
Sempre que a Rota (url) muda eu forço que vá para o topo, para ser mais natural, assim como acontece quando se troca de página, se eu desabilitar, desabilita pra todos.

**Comment by pedrojovelli** [comment]
Irei informar ao Jesse e vemos como podemos proceder.


[image: rs_logo.png]

Pedro Jovelli
Art Director

Mobile: +55 11 96176-2051
Skype: pedrojovelli
rioslumstudio.com


2018-06-25 1:19 GMT-03:00 Rogério Banquieri <notifications@github.com>:
