### ISSUE TITLE
TEAM - mobile navigation

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#12]
área clicável do carrossel do TEAM talvez esteja muito pequena. No Android é menos comum de clicar na seta e abrir o perfil, mas no iPhone acontece com mais facilidade.

Segue aqui sugestões de setas maiores em SVG:
https://drive.google.com/file/d/1OUjWtfDweKOHSNI6fHKdjZRPVlGfbOXG/view?usp=sharing

https://drive.google.com/file/d/18og9CZso3YSYCb_Md70PMniFHQyGh9Nf/view?usp=sharing

Vídeo:
https://drive.google.com/file/d/1s0bpp27h2cAhJ4K73RRPI3KEFXdKwIB5/view?usp=sharing

**Comment by robanquieri** [comment]
Na verdade a área clicável era muito grande e da seta muito pequena. Alterei a área clicável para a área da imagem, funcionou bem.

**Comment by pedrojovelli** [comment]
MIke. The clickable area still not with a healthy area.

Please, if you can make it bigger, in a way that the user can open the modal only when they click over the icon or the photo, that will be better.

Reference that might be helpful
https://drive.google.com/file/d/1qLhLA47RsJvTDk2qbafNkGM05_LwtN4P/view?usp=sharing
