### ISSUE TITLE
WORK - Maven Women substituir imagens

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#12]
Imagens com baixa qualidade atualmente.

Por favor, substituir pelas seguintes:

https://drive.google.com/file/d/177EnGp03aItxrX4ipyLxhi9xrA8tIWS5/view?usp=sharing

![xs](https://user-images.githubusercontent.com/15367213/42129394-cb892dd2-7c99-11e8-9b83-bed3105c7d72.jpg)

![screen shot 2018-06-30 at 7 18 59 pm](https://user-images.githubusercontent.com/15367213/42129430-821c63d4-7c9a-11e8-99cf-fc46814c3118.png)

**Comment by robanquieri** [comment]
feito
