### ISSUE TITLE
WORK Gallery text

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#13]
![home_openportfolio](https://user-images.githubusercontent.com/15367213/41820992-8e9e28f2-77b0-11e8-90f9-d5aaf7d50907.jpg)

Gostaria de pedir para diminuir a imagem proporcionalmente (talvez uns 25%), de forma que caiba o texto de descrição abaixo e mostre na tela sem ter que scrollar...

**Comment by robanquieri** [comment]
Não tem texto e a imagem quem deve diminuir é você.

**Comment by pedrojovelli** [comment]
Sugestão de largura para as imagens?
Posso gerar imagem menor, só me preocupo com a questão de responsividade.

Proveremos textos hoje.

**Comment by pedrojovelli** [comment]
Então velho, uma pergunta.

é possível reduzir a % de width da imagem no css?

Fiz um teste rapidão aqui só pra ter uma idéia ...

![screen shot 2018-06-26 at 8 58 51 am](https://user-images.githubu
sercontent.com/15367213/41910357-cc2dfc86-791f-11e8-8301-c13a45f0f322.png)


70% por exemplo fará com que a imagem fique inteira disposta numa tela comum (13" de macbook) e podemos adicionar as descrições na parte de baixo da img.

![screen shot 2018-06-26 at 8 59 18 am](https://user-images.githubusercontent.com/15367213/41910375-d6399f5a-791f-11e8-88d5-9bcdd2542f7f.png)

Se precisar gerar as imagens novamente, eu gero, só preciso ver contigo um formato ideal para evitar mais uma leva de refação.

**Comment by robanquieri** [comment]
Você assume o risco de que não irá funcionar "bem" em outros tamanhos de tela?

**Comment by pedrojovelli** [comment]
Estamos em fase de teste. 
Sendo assim, podemos testar em diferentes telas nos próximos dias.

Pelo visto você tem intenção em manter em 100%, sendo assim, a imagem deveria ter menos altura para facilitar a inserção do texto na parte de baixo, é isso?

Prefere que eu gere algumas imagens com menos altura para testarmos?

**Comment by robanquieri** [comment]
Entendo que não estamos em fase de teste, se fosse uma fase de teste você não teria porque ter gerado todas as imagens do carousel. Você viu como estava antes de gerar e não teve essa atenção. O correto é manter os 100%, mas se a sua decisão for mudar para 70%, posso fazer, desde que você assuma o risco de eventuais consequências.

**Comment by pedrojovelli** [comment]
Pelo visto você tem intenção em manter em 100%, sendo assim, a imagem deveria ter menos altura para facilitar a inserção do texto na parte de baixo, é isso?

Prefere que eu gere algumas imagens com menos altura para testarmos?

**Comment by pedrojovelli** [comment]
Podemos executar o teste de menos altura antes de prosseguir com 70% por agora?

**Comment by pedrojovelli** [comment]
Ok. Gerando imagens + textos agora (se puder implementar os textos agora em quesito de teste, amanhã irei passar todos pra ti).

**Comment by pedrojovelli** [comment]
_img 01:_

**Brand Package**
RioSlum Studio developed a comprehensive brand package based on Adelante’s refreshed assets that included items ranging from one pager and PPT templates to t-shirts and business cards. 

_img 02:_

**Brand Package**
RioSlum Studio developed a comprehensive brand package based on Adelante’s refreshed assets that included items ranging from one pager and PPT templates to t-shirts and business cards. 

_img 03:_

**Brand Package**
RioSlum Studio developed a comprehensive brand package based on Adelante’s refreshed assets that included items ranging from one pager and PPT templates to t-shirts and business cards. 


![01](https://user-images.githubusercontent.com/15367213/41951609-0fc9caa6-79a2-11e8-9ced-93b496ac5c34.jpg)
![02](https://user-images.githubusercontent.com/15367213/41951610-0fe6bd46-79a2-11e8-8dea-3c92866f38a3.jpg)
![03](https://user-images.githubusercontent.com/15367213/41951611-10035118-79a2-11e8-9a54-4c13964d37cb.jpg)

**Comment by pedrojovelli** [comment]
Reference for placing texts at the bottom:

title font size: 16px ( font DIN MEDIUM )
description font size: 16px  ( font DIN LIGHT )

![home_openportfolio](https://user-images.githubusercontent.com/15367213/41951712-ab96c2ae-79a2-11e8-8334-bff3d67fed6c.jpg)

**Comment by robanquieri** [comment]
O texto muda por imagem? Nos exemplos que você forneceu, são todos iguais.

**Comment by pedrojovelli** [comment]
Sim. O texto muda por imagem.

Nesse caso o texto é o mesmo. Estou pegando os textos de nosso portfolio em PDF.

**Comment by robanquieri** [comment]
Certo, o único problema é o titulo, precisa ser o mesmo pra todos.

**Comment by robanquieri** [comment]
Não dá, precisa ser genérico.

**Comment by robanquieri** [comment]
Deixa, resolvi aqui.

**Comment by robanquieri** [comment]
Eu subi as imagens, dá uma conferida http://banquieri.com/rioslum/#/portfolio/adelante, se estiver ok ajusta as outras e me manda os textos

**Comment by pedrojovelli** [comment]
Cara, 600px de altura para as imagens fica bom, mas seria bacana colocar o texto um pouco sobre a imagem para encaixar 100% numa tela 13"..

Tirei um print aqui de uma gambiarra que fiz com margin-top -100px ...

Podemos fazer dessa forma? e eu me comprometo em gerar as imagens e deixar espaço na parte de baixo para ter um encaixe amigável do texto.

![screen shot 2018-06-27 at 9 40 31 pm](https://user-images.githubusercontent.com/15367213/42006995-a31abdea-7a53-11e8-8448-a7ff3e6e6f68.png)

**Comment by robanquieri** [comment]
Ok, no problem.

**Comment by robanquieri** [comment]
Tem noção que o texto deverá ser no máximo em 3 linhas.

**Comment by pedrojovelli** [comment]
Sim. Se estourar peço para os senhores que o fizeram reduzirem ! 

_o/

**Comment by robanquieri** [comment]
Não vai estourar, vai subir pra dentro da imagem.

**Comment by pedrojovelli** [comment]
podcrer.

Blz ... se cobrir imagem, vou pedir pra eles reduzirem !

**Comment by robanquieri** [comment]
Done
