### ISSUE TITLE
Margins

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#14]
Please, try keeping similar or the same margins on the parallax sessions.
![margins](https://user-images.githubusercontent.com/15367213/33192785-a201adb2-d0ab-11e7-96b5-1da77d4971b6.jpg)

**Comment by robanquieri** [comment]
All sections have equal **PADDING** (Internal space is padding, outer space is margin).

![60px](https://user-images.githubusercontent.com/4391611/33247591-5d621f68-d306-11e7-9d42-ed12eb855d09.jpg)
