### ISSUE TITLE
WORK - Power to Grow replace image

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#14]
Por favor, substituir a xs.jpg por esta:

https://drive.google.com/file/d/1ITLML35ggC4NpTr_QKoFvQzTV3kjj_nu/view?usp=sharing

print for ur reference:
![screen shot 2018-06-30 at 7 37 42 pm](https://user-images.githubusercontent.com/15367213/42129527-1fccfc86-7c9d-11e8-9089-7926c6b59c40.png)

**Comment by robanquieri** [comment]
feito
