### ISSUE TITLE
WORK - Parallax banner button hover

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#16]
Take out the hover underline
Preferentially make the entire square clickable

![screen shot 2018-06-24 at 1 29 35 pm](https://user-images.githubusercontent.com/15367213/41821147-b36e3e04-77b2-11e8-9f73-b8d3f75e8c76.png)
![screen shot 2018-06-24 at 1 29 31 pm](https://user-images.githubusercontent.com/15367213/41821148-b389a5ae-77b2-11e8-9f1f-468017a5b742.png)

**Comment by robanquieri** [comment]
Feito
