### ISSUE TITLE
WORK - Services Text

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#19]
Replace text on the image for the text below:

Whether you're launching or re-launching your brand, undergoing a refresh, or seeking new audiences, RioSlum Studio will find your original voice. RioSlum Studio engages with clients on a variety of levels and offers services in both English and Spanish.

![screen shot 2018-06-24 at 1 37 50 pm](https://user-images.githubusercontent.com/15367213/41821234-e3734846-77b3-11e8-9295-9d5e7241ca86.png)

**Comment by robanquieri** [comment]
Feito
