### ISSUE TITLE
WORK - Menu links

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#2]
link ROVERING

Quando passa o mouse sobre os links do menu no topo, gostaríamos de ver contigo se da para pintar a palavra, no mesmo esquema dos rovers dos ícones.

Cada palavra teria uma cor (cor respectiva de cada página)

When you hover over the words of the top-level navigation, the color traces the word/letters with whatever color is selected for that page. However, when you click on it, it takes you to that page, and then locks into that color for that page (with whatever color is selected for that page).

**Comment by robanquieri** [comment]
Muito bom, mas não é possível.

**Comment by pedrojovelli** [comment]
Por favor, se puder fazer o mesmo efeito de hover do submenu no menu principal.

Uma sugestão seria deixar a linha da página que o user está já sublinhada em baixo.

**Comment by robanquieri** [comment]
Feito
