### ISSUE TITLE
SIGORA GALLERY TEXTS

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#2]
Texto 1: OK

Texto 2: OK

Texto 3: OK

Texto 4: 
**Brand Package**
RioSlum Studio conducted a brand study, produced a conceptual direction, and designed
a brand package with design standards, language standards, communications strategy,
and visual and language templates

Texto 5:
**Pitch Deck**
RioSlum STudio refined client language and designed an animated pitch deck.

**Comment by robanquieri** [comment]
done
