### ISSUE TITLE
WHAT WE OFFER - Mobile navigation arrows

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#21]
MIke. The clickable area still not with a healthy area.

Please, if you can make it bigger, in a way that the user can open the modal only when they click over the icon or the photo, that will be better.

Reference that might be helpful
https://drive.google.com/file/d/1qLhLA47RsJvTDk2qbafNkGM05_LwtN4P/view?usp=sharing

**Comment by robanquieri** [comment]
Fixed.
