### ISSUE TITLE
TEAM - mobile scrolling over arrows

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#22]
The current carousel is making the scrolling elements going below the arrows.
Is it possible to make the elements disappear before crossing to the arrows?

Reference from what's happening right now:
https://drive.google.com/file/d/1NpDvCGcz75VTCYZ6ogxPPHL_FGx-uDlo/view?usp=sharing

**Comment by robanquieri** [comment]
Fixed.
