### ISSUE TITLE
STARTUP text adjust

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#22]
Please, change STARTUP to STARTUPS ( with S at the end)

at the menu and at the title.

![screen shot 2018-06-24 at 1 50 06 pm](https://user-images.githubusercontent.com/15367213/41821350-938b10b4-77b5-11e8-8fe8-6ed54aedbd6c.png)

**Comment by pedrojovelli** [comment]
Please, change STARTUP to STARTUPS ( with S at the end).

STARTUPS

**Comment by robanquieri** [comment]
Done
