### ISSUE TITLE
FOOTER - Contact text adjust

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#24]
Change Title and text:

**CONTACT US**
Spark a conversation with RioSlum Studio.

![screen shot 2018-06-24 at 2 09 06 pm](https://user-images.githubusercontent.com/15367213/41821513-3521ea54-77b8-11e8-8f90-4e173f28e929.png)

Retirar exclamação do BTN de enviar:

![screen shot 2018-06-24 at 2 11 38 pm](https://user-images.githubusercontent.com/15367213/41821536-9f9231aa-77b8-11e8-8f26-6cae69776732.png)

**Comment by robanquieri** [comment]
Feito
