### ISSUE TITLE
FOOTER - Text adjust

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#25]
Replace text at the footer for this one:

RioSlum Studio offers branding, design, messaging, strategy, and videography services to daring companies with bold vision. We build compelling brands that evoke emotion, demand attention, and attract business.

![screen shot 2018-06-24 at 2 16 57 pm](https://user-images.githubusercontent.com/15367213/41821572-517a9d94-77b9-11e8-8057-a8044a617862.png)

Add Call us at and Visit us at, like the mockup below:

![screen shot 2018-06-24 at 2 21 56 pm](https://user-images.githubusercontent.com/15367213/41821624-07067610-77ba-11e8-8a96-055ee486aa89.png)

**Comment by robanquieri** [comment]
Feito
