### ISSUE TITLE
FOOTER - Social Media links adjust

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#26]
Deixar links do FACEBOOK / INSTAGRAM / VIMEO

Se possível, alinhar estes links verticais com os outros elementos (texto e logo como mostra na linha azul)

![screen shot 2018-06-24 at 2 33 06 pm](https://user-images.githubusercontent.com/15367213/41821769-9dd15dac-77bb-11e8-9d19-8489c6bb8ff6.png)

**Comment by robanquieri** [comment]
Feito
