### ISSUE TITLE
PAGE TRANSITIONS

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#27]
Jesse would like to discuss with us possibilities for making the transition smoother.

Can we set a quick meeting this week to talk a bit about this?

**Comment by robanquieri** [comment]
Voce pode atrasar o tempo de carregamento da página, estava em 300ms, deixei em 500ms, mais do que isso vai parecer um defeito.

**Comment by pedrojovelli** [comment]
Blz. Pode fechar Este. Acho que está bem melhor ..

Uma pergunta. É possível colocar também poster images para os vídeos de header? aqueles em autoplay.

**Comment by robanquieri** [comment]
Eu já te expliquei umas 4 vezes. Mande o primeiro frame de cada vídeo de background mais o da Home, por favor, sempre que tiver essa dúvida, retorne a este post.

**Comment by pedrojovelli** [comment]
Ok. Irei prover todas as imagens de background + orientação para facilitar aplicação.
