### ISSUE TITLE
ABOUT - Text structure / adjusts

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#29]
Add this paragraph at the beginning:

RioSlum Studio offers branding, design, messaging, strategy, and videography services to daring companies across the globe. It’s our mission to turn your vision into something tangible, beautiful, and relatable.

![aboutrio](https://user-images.githubusercontent.com/15367213/41822108-04ba6324-77c1-11e8-8d2e-b0d6429596e5.jpg)

ITALIC FONT:
Din Italic here >>>
https://drive.google.com/file/d/1yW6srXBmo0Jqg0F20yCEMo8TuD2a43Fg/view?usp=sharing

**Comment by robanquieri** [comment]
Feito
