### ISSUE TITLE
WORK - Menu / work link

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#3]
Basicamente sobre o item 3, o Jesse quer que o link WORK fique laranja somente enquanto estiver scrollando sobre a parte de portfolio ... quando chegar naquele parallax de "ABOUT RIOSLUM", o link volta a ser cinza escuro.

Work Button 

•	When you arrive to the website, the Work button should not be highlighted. 

•	When you click on the work button, it then scrolls up and then takes you to the work section. 

•	Current, there is no Work page, so the Work button only remains highlighted while you are in the Work section. Once you leave the Work section (via scrolling), Work then switches to black and all the top level navigation remains black on the homepage. The only time the top level navigation on the homepage changes colors from black, is when you are in the Work section.

**Comment by robanquieri** [comment]
Estamos com muita manipulação de scroll, e isso está trazendo conflitos. Ao invés de pintar o Work de laranja, podemos remove-lo do menu já que é a "home" e o click no logo leva para a home, ou mudar o "Work" para "Home".

**Comment by pedrojovelli** [comment]
Jesse would like to ask you if this is possible to do.

This is bothering him a lot ... 

if this is not conflicts with other interactions. We should keep it ( disable the highlight on WORK after passes through the work gallery)

**Comment by robanquieri** [comment]
Done.
