### ISSUE TITLE
ABOUT - Team section

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#30]
- Centralizar nomes e títulos
- Usar imagens circulares (irei enviar as imagens)

Deixar Jesse / Pedro na primeira linha

ELYSA / LUCIA / ROGERIO na segunda linha

![screen shot 2018-06-24 at 5 32 32 pm](https://user-images.githubusercontent.com/15367213/41823329-b1b1de5a-77d4-11e8-8d06-91b175d3b5ae.png)

**Comment by robanquieri** [comment]
Feito. Posso arredondar as imagens no CSS, mas elas precisam ser quadradas.

**Comment by pedrojovelli** [comment]
![jesse_profile_squared](https://user-images.githubusercontent.com/15367213/41951115-a0a8baee-799f-11e8-9152-7e96d3dd2a8d.jpg)


Segue imagem para placeholder

**Comment by robanquieri** [comment]
Done
