### ISSUE TITLE
ABOUT - Change Text 'Where We Are'

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#31]
Alterar texto para "Staff Locations" (no título e no submenu do topo)

Alterar texto seguinte ao título:
RioSlum Studio is officially incorporated in Washington, DC and Philadelphia, PA. The firm also has a staff presence in Brazil and Guatemala.

![screen shot 2018-06-24 at 3 29 52 pm](https://user-images.githubusercontent.com/15367213/41822271-8acb84b4-77c3-11e8-864f-fe9828888a53.png)

**Comment by robanquieri** [comment]
Feito.
