### ISSUE TITLE
SERVICES - Add Bullets on the lists

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#33]
Please, add bullets.

![arrows_bullets](https://user-images.githubusercontent.com/15367213/41822374-edf986fc-77c4-11e8-9ecc-00954ffd3ddb.jpg)

Arrows are here in SVG:
https://drive.google.com/file/d/1131c0dHJkA1slLNAD4ceWwftHYR3AMOp/view?usp=sharing

**Comment by robanquieri** [comment]
I don't understand, I already add bullets...

<img width="53" alt="image" src="https://user-images.githubusercontent.com/4391611/41951411-3d1f17dc-79a1-11e8-899d-c886d2386dd5.png">

**Comment by pedrojovelli** [comment]
interesting ..

we're not being able to see it .. both Jesse and I.

For your reference:

![screen shot 2018-06-27 at 12 33 28 am](https://user-images.githubusercontent.com/15367213/41951556-cf08a208-79a1-11e8-9c43-08b81dfd0cf8.png)

**Comment by pedrojovelli** [comment]
Maybe the image is missing on the server..

**Comment by robanquieri** [comment]
Fixed.
