### ISSUE TITLE
STARTUPS - Change text

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#34]
Please, delete button and replace the following text:

The RioSlum Studio leadership team met while working at a Latin American business accelerator. Working with startups and social enterprises is in the very DNA of our business and is the inspiration for our name.

RioSlum Studio has a practice dedicated to helping entrepreneurs across the globe achieve their business goals through branding, design, marketing, communications, and videography.

![text](https://user-images.githubusercontent.com/15367213/41822517-3793198e-77c7-11e8-986a-b9826c6219a8.jpg)

**Comment by robanquieri** [comment]
Done
