### ISSUE TITLE
STARTUPS - Text change title

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#35]
Change title  and link at the submenu for this:
**RioSlum Studio & Startups**

![blehbleh](https://user-images.githubusercontent.com/15367213/41822547-e16ab4d0-77c7-11e8-841b-ab1d00bc3d5a.jpg)

RioSlum Studio partners with accelerators, incubators, and entrepreneur networks around the world to offer flexible, affordable services to groundbreaking startups. On a case-by-case basis, RioSlum Studio will work with startups outside of existing partnerships. Below are our current entrepreneur-oriented partnerships:

**Comment by robanquieri** [comment]
Done
