### ISSUE TITLE
STARTUPS - Change text / icon structure

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#36]
![screen shot 2018-06-24 at 4 31 54 pm](https://user-images.githubusercontent.com/15367213/41822839-44fe5782-77cc-11e8-92f6-25663914d521.png)

RioSlum Studio partners with accelerators, incubators, and entrepreneur networks around the world to offer flexible, affordable services to groundbreaking startups through preferred vendor engagements. On a case-by-case basis, RioSlum Studio will work with startups outside of existing partnerships. Below are our current entrepreneur-oriented partnerships:

logos are here:
https://drive.google.com/drive/folders/18qUm2jsy8QZsWXbMhpSQvDb5aNmBoWDC?usp=sharing

**Comment by robanquieri** [comment]
Onde é isso?

**Comment by pedrojovelli** [comment]
No meio da página STARTUPS. Esse bloco aqui:

![screen shot 2018-06-27 at 12 53 03 am](https://user-images.githubusercontent.com/15367213/41952088-88a5a0b0-79a4-11e8-8e96-5fa3eda13759.png)

**Comment by robanquieri** [comment]
Sério que mudou a estrutura?

**Comment by pedrojovelli** [comment]
Sorry about that buddy.

Conversei com o Jesse ontem referente ao fato de não poder alterar coisas após elaborado / revisado e aprovado no design ...  enfim...  Estou segurando edições como eu posso... a galerinha não tem muita noção de web.
