### ISSUE TITLE
STARTUPS - Add Title Testimonials

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#37]
Add TESTIMONIALS title    ( make the link for the submenu goes to it )

![screen shot 2018-06-24 at 4 38 34 pm](https://user-images.githubusercontent.com/15367213/41822895-23436528-77cd-11e8-9cb4-9909d310530a.png)

**Comment by robanquieri** [comment]
Fonte? Tamanho de fonte?

**Comment by pedrojovelli** [comment]
font-size: 40px;

Segue o mesmo estilo dos títulos acima.
Referência de estilo do título:

![screen shot 2018-06-28 at 12 47 11 am](https://user-images.githubusercontent.com/15367213/42012081-e48ab384-7a6c-11e8-8e7d-b2796df12463.png)

**Comment by robanquieri** [comment]
Done
