### ISSUE TITLE
STARTUPS - Testimonials

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#38]
![screen shot 2018-06-24 at 5 05 12 pm](https://user-images.githubusercontent.com/15367213/41823139-e77bbee2-77d0-11e8-877f-13fc23e7df3c.png)

Gostaríamos de aplicar um slider para os 6 testimonials que possuímos.

Quanto a transição. O que acha melhor? um slider que passe de um para o outro fazendo um drag, tipo um carrocel de forma automática de tantos em tantos segundos, e se parar o cursor sobre, ele para de mover.. ?

Se puder dar uma força com relação a isso.

Estes são os textos:
https://docs.google.com/document/d/10CZ9lkMoATYMBp-I4JEHXBcgD3xx4X0JVhkdNYCmLQw/edit?usp=sharing

Estas são as fotos de perfil nomeadas com nome da empresa:
https://drive.google.com/drive/folders/1lRqPgYtncvF4mlj4SdeiTJL42Sp5Woh6?usp=sharing

**Comment by robanquieri** [comment]
Done
