### ISSUE TITLE
WORK - Submenu links hovers

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#4]
![screen shot 2018-06-24 at 11 58 55 am](https://user-images.githubusercontent.com/15367213/41820308-346565e4-77a6-11e8-8cd4-c579c3805788.png)

Quando passa o mouse sobre os links do submenu. Gostaríamos que tivesse esse efeito no sublinhado:

http://www.jbdunckel.com/?lang=en  ( checar hover do menu no topo)

(( porém, a linha ficaria em baixo do texto, como um underline, mas neste comportamento ))

**Comment by robanquieri** [comment]
Feito
