### ISSUE TITLE
WORK - MavenWomen video display

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#4]
![screen shot 2018-06-30 at 5 47 25 pm](https://user-images.githubusercontent.com/15367213/42128979-d7cf1fae-7c8d-11e8-8015-f4cdf5d61391.png)

The way the video is placed currently covers the description below.

Please, any adjust to make the video a bit smaller and show the description below all the time is good to go.

![sugestao](https://user-images.githubusercontent.com/15367213/42129020-22f1ffdc-7c8f-11e8-9020-d8623205bd59.jpg)

**Comment by robanquieri** [comment]
http://banquieri.com/rioslum/#/portfolio/maven-women

Aperta COMMAND + SHIFT + R pra limpar o cache do browser.

**Comment by pedrojovelli** [comment]
Está ótimo.
