### ISSUE TITLE
MOBILE - What We Offer

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#40]
ON MOBILE:

When you open the modal. It opens pretty well.

When you click to close it. the carousel give a blink right after it closes. Is it possible to remove this glitch?

**Comment by robanquieri** [comment]
unfortunately it is not possible, but you be able to choose another exit effect in: https://daneden.github.io/animate.css/

**Comment by pedrojovelli** [comment]
SlideInDown para fechar o modal.

Acha que isso irá eliminar a aparição demorada do carrocel ?

**Comment by pedrojovelli** [comment]
Mike, vi que vocÊ aplicou o mesmo efeito que aplicou na saída do TEAM. Enfim, ficou inclusive mais carregado essa fechada do modal. Se puder remover esse efeito e deixar o mais seco o possível.... iremos evitar discussões com o Jesse. Como eu falei, ele é 100% leigo em web. Pra ele não tem muita explicação, ou está certo ou está errado...

**Comment by robanquieri** [comment]
Quando o plugin é inicializado eu passo um efeito de entrada e um de saída. Vou remover os efeitos, mas irá ficar seco, sem vida.
