### ISSUE TITLE
Substituir imagens em Portfolio

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#43]
mandei no e-mail. Não consegui terminá-las ontem. Só substituir

**Comment by pedrojovelli** [comment]
Mike. As imagens ainda estão com descrição pequena, bem como a imagem da seta não foi substituída. Acessei via browser anônimo achando que era cache, mas acho que não ...

Segue prints do e-mail...

![screen shot 2017-12-16 at 9 43 15 am](https://user-images.githubusercontent.com/15367213/34070071-b7d3e73a-e245-11e7-869f-5fc9385ac848.png)

![screen shot 2017-12-16 at 9 44 41 am](https://user-images.githubusercontent.com/15367213/34070076-c7164616-e245-11e7-9804-0d2e30520a37.png)

**Comment by robanquieri** [comment]
Eu sobrescrevi com as imagens que estava no zip, quanto as setas, veja bem, as que você enviou não existem no site, inspecione as setas que deseja mudar, pegue o nome real delas e me mande um novo zip.

**Comment by pedrojovelli** [comment]
Mike, pelo que entendi, o SVG está direto no código. Não há um arquivo SVG da seta de portfolio ...

![screen shot 2017-12-18 at 4 19 52 pm](https://user-images.githubusercontent.com/15367213/34121341-d6f2cf8e-e40f-11e7-89dd-fc7f0f02b8f9.png)


![screen shot 2017-12-18 at 4 36 06 pm](https://user-images.githubusercontent.com/15367213/34121858-a81c8a86-e411-11e7-998f-18c15f8a15b8.png)


Segue setas para portfolio:
https://drive.google.com/drive/folders/1wMBOqQqrFnFJzM5CdiZYGp4x0ss_YaHD?usp=sharing
