### ISSUE TITLE
ABOUT - BG Poster Inside Video

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#43]
Segue imagem de poster dos vídeos das páginas internas (headers only):

https://drive.google.com/file/d/1qLABNk94NZZ24qgcENWg19hPlZIx2DXH/view?usp=sharing

![screen shot 2018-06-27 at 9 40 55 pm](https://user-images.githubusercontent.com/15367213/42006880-dd45092c-7a52-11e8-9a50-c7717608f177.png)

**Comment by robanquieri** [comment]
Não entendi. Pedro, precisa ser o primeiro frame do vídeo, pra que o usuário não perceba o carregamento...

**Comment by pedrojovelli** [comment]
https://drive.google.com/file/d/1OI1LtjFZ4bJUCijOtrnq_U9Um-pWRlI6/view?usp=sharing

**Comment by robanquieri** [comment]
Todos os vídeos do header das páginas são iguais?

**Comment by pedrojovelli** [comment]
Não.

Este seria o poster específico para ABOUT

**Comment by robanquieri** [comment]
Done
