### ISSUE TITLE
TEAM area weird blink

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#44]
When you click to close the profile modal, it blinks with a BLACK tone covering the entire screen.

Can we do not have this behaviour?  or make it be a fed-out from white to transparent and not BLACK to transparent?

**Comment by pedrojovelli** [comment]
Vi o efeito aplicado. Estou bem certo que o Jesse irá achar aquilo estranhão. O Jesse é 100% leigo. Se quiser escrever alguma explicação sobre aquela caixa preta com animação na hora de fechar o modal.

Não temos interesse em ter qualquer interação na hora de fechar. Clicando em fechar, se puder somente desaparecer as infos de TEAM e WHAT WE OFFER, sem nenhum blink, já está de bom tamanho.

**Comment by robanquieri** [comment]
Vou remover.
