### ISSUE TITLE
Change CONTACT header video

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#46]
Change the soccer court clip for this one below:

https://drive.google.com/file/d/1Barsxv0lTV7ffwK2hlOz1SAllrQSzTji/view?usp=sharing

BG poster for this clip:
https://drive.google.com/file/d/1KyeGSYgBVkRYzOLT_IXB-Xx8nNOiESVW/view?usp=sharing

**Comment by robanquieri** [comment]
Done
