### ISSUE TITLE
Elysa text edit ABOUT

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#50]
"Stun- ning"    -->    "**Stunning**"

![screen shot 2018-06-27 at 10 37 41 pm](https://user-images.githubusercontent.com/15367213/42008224-c5c56758-7a5a-11e8-94cf-7403ba7f5791.png)

======

"Jour- ney"    -->   "**journey**"
![screen shot 2018-06-27 at 10 38 31 pm](https://user-images.githubusercontent.com/15367213/42008246-da51f09c-7a5a-11e8-9380-5a116ea24807.png)

======

**Delete origin paragraph**

![screen shot 2018-06-27 at 10 40 31 pm](https://user-images.githubusercontent.com/15367213/42008316-33227584-7a5b-11e8-815d-098a6d5a6e45.png)

**Comment by robanquieri** [comment]
done
