### ISSUE TITLE
Elysa text edit ABOUT (maps)

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#51]
- first sentence of cially --> "**officially**" 
- first sentence Wash- ington --> "**Washington**"

![screen shot 2018-06-27 at 10 43 18 pm](https://user-images.githubusercontent.com/15367213/42008380-90fc71dc-7a5b-11e8-8af0-5a12694c4147.png)

**Comment by robanquieri** [comment]
done
