### ISSUE TITLE
Elysa text edits SERVICES

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#52]
- Change first sentence on BRANDING to: 
**Develop a unified, multi-dimensional identity that reflects your core values, engages your customers, and leaves a lasting impression.**

- MESSAGING:
hash-tag --> "**Hashtag**"

- Change first sentence on STRATEGY:
**Position your brand to identify and engage with a larger audience while leveraging communications to convert customers into allies and ambassadors.**

**Comment by robanquieri** [comment]
done
