### ISSUE TITLE
WORK - Add Maven Women video

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#54]
Maven Women é um filme.

Se puder colocar este como placeholder + bloco de texto abaixo.
https://vimeo.com/276436955

texto:
**Maven Women Short Film**
RioSlum Studio storyboarded, produced, and edited a short film for Maven Women to premier at the State of Fashion event in Arnhem, Holland. The film was also featured on Maven Women's website and social media.

**Comment by robanquieri** [comment]
Então, não estava no escopo ter vídeos nessa área. Enfim, mesmo esquema, preciso do primeiro frame do vídeo.

**Comment by pedrojovelli** [comment]
Perfeito. Vou prover

**Comment by robanquieri** [comment]
Faltou o primeiro frame do vídeo....

**Comment by pedrojovelli** [comment]
Então, pode colocar essa imagem embaçada com logo ao centro como primeira imagem para MAVEN WOMEN ?

**Comment by robanquieri** [comment]
done
