### ISSUE TITLE
ABOUT - Replace profile photos

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#55]
All team except Jesse that is already there:
https://drive.google.com/drive/folders/1XVfyDz-mMkHOAUWFq-hYXceeqqqMHjl6?usp=sharing

Or you can pick the images here:

![team_elysa](https://user-images.githubusercontent.com/15367213/42010110-91bd7a6e-7a63-11e8-93c2-824e091809c7.jpg)

![team_lucia](https://user-images.githubusercontent.com/15367213/42010119-957f3cbe-7a63-11e8-8736-faaaf42ca68b.jpg)

![team_rogerio](https://user-images.githubusercontent.com/15367213/42010127-9a5f65ec-7a63-11e8-838b-80dc0adff182.jpg)

![team_pedro](https://user-images.githubusercontent.com/15367213/42010130-9f5cc878-7a63-11e8-8d58-4b08e3deed43.jpg)

**Comment by robanquieri** [comment]
Não são as imagens finais certo? Me manda as finais...
