### ISSUE TITLE
GALLERY TEXTS - POWER TO GROW

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#56]
-----

**Comment by pedrojovelli** [comment]
- POWER TO GROW:

1
**La Red & Challenge Brand Development**
RioSlum Studio developed new brands for both La Red and its Challenge entitled
“Power to Grow”. Assets created included a new La Red logo, a new Challenge logo,
and complete brand packages for both.

2
**Challenge Digital Ads**
Designed, launched, and placed a series of digital ads in English and in Spanish to
attract applicants to the “Power to Grow” Challenge. 

3
**Challenge Website**
For the launch of the 2018 “Power to Grow” Challenge, RioSlum Studio designed,
launched, and maintained a microsite in both English and Spanish. 

4
**Challenge Digital Ads**
Designed, launched, and placed a series of digital ads in English and in Spanish to
attract applicants to the “Power to Grow” Challenge. 

5
**Challenge Digital Ads**
Designed, launched, and placed a series of digital ads in English and in Spanish to
attract applicants to the “Power to Grow” Challenge.

**Comment by robanquieri** [comment]
done
