### ISSUE TITLE
GALLERY TEXTS  - Keteka

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#60]
1.
**Brand Package**
RioSlum Studio created a brand package that included language
standards, design standards, and adaptable templates. 

2.
**Brand Applications**
RioSlum Studio applied the brand to a variety of collateral, including
postcards, social media posts, and physical collateral. RioSlum Studio
also outlined best practices for asset application.

3.
**Web Pages**
RioSlum Studio adapted select Keteka web pages to incorporate the
updated, cinematic brand, improve UX, and increase conversions.

**Comment by robanquieri** [comment]
done
