### ISSUE TITLE
GALLERY TEXTS - Dreaming Out Loud

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#62]
1.
**Annual Report**
RioSlum Studio produced Dreaming Out Loud’s 2017 Annual
Report to comply with updated brand standards.

2.
**Flyer** 
Event flyer to comply with updated brand standards.

3.
**Food Panel Flyer**
 Annual report RioSlum Studio produced an event
flyer to comply with updated brand standards.

**Comment by robanquieri** [comment]
done
