### ISSUE TITLE
GALLERY TEXTS - AfricaB2B

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#63]
1.
**Pitch Deck**
RioSlum Studio refined client language and
created an original one one-pager and pitch
deck (design and language).

2.
**Brand Identity**
RioSlum Studio created brand guidelines, enabling
the client to maintain its brand identity across a
 variety of collateral.

3.
**One Pager**
RioSlum Studio refined client language and
created an original one one-pager and pitch
deck (design and language).

**Comment by robanquieri** [comment]
done
