### ISSUE TITLE
TEXT ADJUST - TEAM PEDRO - Add period at the end

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#64]
Pedro has accumulated over 14 years of graphic design experience working in his home country of Brazil, as well as in the United States. He believes a strong visual identity and bold, dramatic designs are critical elements to helping enterprises reach mainstream, global audiences. Over the last decade, Pedro has worked as a graphic designer, interactive website developer, front-end designer, and art director. For more than five years, he has worked with Agora building daring, memorable brands for both Agora Partnerships and portfolio companies in its Accelerator. At RioSlum Studio, Pedro leads design and art direction.

**Comment by robanquieri** [comment]
done
