### ISSUE TITLE
FOOTER - Replace links Social Media

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#68]
Please, replace the social media links for just these two:

VIMEO: https://vimeo.com/rioslumstudio
FACEBOOK: https://www.facebook.com/rioslumstudio/

![screen shot 2018-06-28 at 10 11 58 am](https://user-images.githubusercontent.com/15367213/42036394-bc0994c6-7abb-11e8-9a43-b88576374ea7.png)

**Comment by robanquieri** [comment]
done
