### ISSUE TITLE
WORK - Alignment Hover

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#69]
When page compressed (half of computer screen), Agora Partnerships and Dreaming Out Loud's text align left, all others are centered

![screen shot 2018-06-28 at 9 42 00 am](https://user-images.githubusercontent.com/15367213/42034840-aaeb3932-7ab7-11e8-9ddb-89e99c9212f2.png)

![screen shot 2018-06-28 at 9 42 05 am](https://user-images.githubusercontent.com/15367213/42034848-ad48ee90-7ab7-11e8-949b-075c4bff860b.png)

**Comment by pedrojovelli** [comment]
- AGORA muda o alinhamento em 1060px largura

- DREAMING OUT LOUD muda o alinhamento em 1030px largura

Does that help you?

**Comment by robanquieri** [comment]
done
