### ISSUE TITLE
SUBMENU Behaviour

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#7]
Ref de preenchimento dos botões conforme scrolla http://rioslumstudio.com/

Pode me chamar com relação a esse comportamento para os submenus?

Gostaria de saber sua opinião com relação a isso ..

**Comment by robanquieri** [comment]
Eu discordo desse recurso porque o submenu está sendo escondido, se ele ficasse visível o tempo todo ai eu concordaria.

**Comment by pedrojovelli** [comment]
Ok. Spoke with Jesse about that.

COuld you close this issue ?

Thanks
