### ISSUE TITLE
WORK Text edit

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#72]
STARTUPS PARALLAX:

We launched RioSlum Studio to ensure all companies, from one-person startups to international corporations, have access to the high-quality branding and communications services they need to command global attention.

![screen shot 2018-06-28 at 9 47 58 am](https://user-images.githubusercontent.com/15367213/42035130-8ab76428-7ab8-11e8-82b4-09b0480a010c.png)

**Comment by robanquieri** [comment]
done
