### ISSUE TITLE
STARTUPS - Testimonials margins

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#73]
Is it possible to leave the spacing automatic between the TESTIMONIALS and the elements below ?

![screen shot 2018-06-28 at 9 50 29 am](https://user-images.githubusercontent.com/15367213/42035208-c4ba74ee-7ab8-11e8-93dc-1c8bd536a36b.png)

Some testimonials are a bit smaller and makes a really big margin:

![screen shot 2018-06-28 at 9 52 04 am](https://user-images.githubusercontent.com/15367213/42035301-fa1899d6-7ab8-11e8-8002-7aabce267b43.png)

**Comment by robanquieri** [comment]
I changed for adaptive height, now the arrows change position according to the height of each slide.

**Comment by pedrojovelli** [comment]
great work ! thanks !
