### ISSUE TITLE
ABOUT TEAM - text edit

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#74]
Please, replace Jesse's profile text:

Jesse brings a wealth of experience working in marketing, communications, and entrepreneurship to the RioSlum Studio team. Jesse has previously worked as a political reporter, photographer, digital media consultant for musicians, and marketing specialist for an investment firm in East Africa. Additionally, Jesse served as Director of Business Development at Agora Partnerships, where he oversaw communications, fundraising, partnerships, and strategy. At RioSlum Studio, Jesse focuses on new business development and directing branding strategy for clients.

**Comment by robanquieri** [comment]
done
