### ISSUE TITLE
ABOUT TEAM - Replace Text

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#75]
Please, replace Elysa's profile text:

Elysa has worked with a range of clients, providing strategy, communications, and marketing services. She believes that the combination of the right language and the right strategy can produce limitless results. Previously, Elysa worked as a political communications consultant for a variety of for-profit, nonprofit, and government clients, Communications Director for an ethical fashion company, political campaign organizer, and Communications Manager at Agora Partnerships. At RioSlum Studio, Elysa is responsible for account management, project execution, and contributes to company strategy development.

**Comment by robanquieri** [comment]
done
