### ISSUE TITLE
ABOUT Text - Replace texts

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#76]
Please, replace Lucia's text:

Lucia is an Industrial Engineer with a passion for creative communication and branding. Italian by birth, citizen of the world by choice, Lucia moved to Guatemala after her MBA at IESE Business School, fascinated by the development challenges of the country. She has worked as the Chief Communication Officer for a local fashion-inspired NGO and is involved in the tech start-up scene of Guatemala. Lucia believes in the transformative potential of communications to both communicate and spark positive change across Latin America.

**Comment by robanquieri** [comment]
done
