### ISSUE TITLE
Parallax image - Services

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#8]
Please, use this image for parallax on SERVICES:

https://drive.google.com/file/d/1fMlGcDRHau9gqL_z4VHNd-HclKh1Vadh/view?usp=sharing

**Comment by robanquieri** [comment]
Tem dois parallax, em qual devo substituir?

**Comment by pedrojovelli** [comment]
Desculpe. Primeiro parallax.

**Comment by robanquieri** [comment]
done
