### ISSUE TITLE
ABOUT - Video

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#8]
De fato, achamos melhor manter o vídeo sem autoplay.

Queríamos que a primeira tela fosse com o logo. Tipo algo assim:
![screen shot 2018-06-24 at 12 25 54 pm](https://user-images.githubusercontent.com/15367213/41820564-0199da7e-77aa-11e8-8db7-226425f56494.png)

Você tem como manipular isso ou seria algo que teríamos de pedir para o cara de MOTION para começar o vídeo com o logo?

**Comment by robanquieri** [comment]
Sim, é uma imagem de "Poster", me manda e adiciono nos vídeos.

**Comment by robanquieri** [comment]
Feito, porem como o fundo da página é branco, não surtiu muito efeito. Sugiro que a imagem tenha o fundo preto.

**Comment by pedrojovelli** [comment]
Ok. 

O mano de motion está agilizando os filmes de SERVICES. Logo iremos passar tudo pra ti + as imagens
