### ISSUE TITLE
PORTFOLIO brand replacement

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#9]
Replace Uncommon Cacao to Agora Partnerships.

Here's the folder where i'll populate with the AGORA files:

https://drive.google.com/drive/folders/1etCbBtQd4f_r6i9KNzTKiUfEnHUmQq4a?usp=sharing

**Comment by robanquieri** [comment]
A pasta está vazia.

**Comment by pedrojovelli** [comment]
Imagens no formato 2 estão lá agora.

**Comment by robanquieri** [comment]
Faltou a xxxl.jpg

**Comment by robanquieri** [comment]
Faltaram as imagens do carousel

**Comment by pedrojovelli** [comment]
XXXL:
https://drive.google.com/file/d/1HgAu5y4A1FQ94Y0l9a2ZA22W_7X8i60n/view?usp=sharing


imagens da galeria:
https://drive.google.com/drive/folders/1qtr117rERs3Lx632lOB3YZVNfr5jisFp?usp=sharing
